# Site
repository: Static Personal Website containing information about myself.
# favicon: Directory of my favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Danish Shah
title: Graduate Student
email: ms3329@cornell.edu
# email_title: Email (Email title override)
phone: +1 (607)-697 5526
# phone_title: Phone (Phone title override)
website: https://danish.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: its_danish1998
github_username:  ms3329
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: im_dannyboy
linkedin_username: sdanish1998
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/winter_profile_picture.jpg
about_content: |
  Hi, my name is Danish Shah, I'm an avid enthusiast in Capital Markets, Engineering & Technology. I love to build projects from scratch or to comprehend existing projects from a bigger perspective to contribute my innovation. My never-ending quest to solve mathematical problems that create tangible results motivated me to step into the Quant world. My passion is to bridge the gap between Quantitative Finance and Data Science to build effective and robust solutions to business problems. 
  
  I aim to add value in key business areas like Predictive Modeling, Quantitative Research & Analysis, Asset Management, Risk Analytics, and relevant verticals. Skilled in multiple programming languages, including Python, C/C++, Java, Scala, and R

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Goldman Sachs
        sub_title: Analyst
        caption: August 2020 - July 2022
        link: https://www.goldmansachs.com/
        description: |
          Global Markets Surveillance Analytics
            - **Data Science**: Performed statistical analysis on trade data using Python, and trained time-series (ARIMA, GARCH) and machine-learning models to study client activity and market signals, to identify predictable patterns in the firm’s transactions
            - **Big Data**: Built distributed computing systems to process global markets data (1.2B+ rows per day) using Hadoop and Spark, and improved data pipeline efficiency by 74% by ensuring optimal distribution of data across parallel MapReduce tasks
            - Collaborated with multiple front and back office teams, developing tools for different upstream/downstream business functions, and helped them with collecting, and analyzing large amounts of data from various sources
            - **Programming**: Developed Java, Scala applications, and APIs to collect, format and write data to hdfs, Hbase, data-lake, etc.
            - Wrote and reviewed code written by other developers in the team, and managed the team’s production releases, version control, UAT testing, etc., overseeing the completion of tasks through the software development cycle
      - layout: left
        title: Anheuser-Busch InBev
        sub_title: Data Scientist
        caption: May - July 2019
        link: http://www.anheuser-busch.com/
        description: |
          Predictive models to measure the cultural fitness of candidates
            - **Data Analytics**: Analyzed and built predictive models (kNN, SVM) on aptitude data to measure cultural fitness of candidates
            - Developed & deployed a web-scraper bot that uses Talent Acquisition tools available in the market for proactive recruitment
      - layout: left
        title: Agnikul Cosmos
        sub_title: Software Developer
        caption: May - July 2018
        link: http://www.agnikul.in/#
        description: |
          Optimization Analysis for the launch vehicle, Trajectory Design & Simulation, and Debris Modeling
            - **Numerical Simulation**: Developed a computer model using Python and MATLAB to simulate rocket launch, and compute the trajectory of the rocket and its payload, along with the dropped stages and debris
            - Programmed a dynamic atmosphere model with wind profile and randomness based on academic research; integrated this with the trajectory program and ran Monte-Carlo simulations to compute uncertainties in the predicted trajectories
  - title: Education
    layout: list
    content:
      - layout: top
        title: Cornell University
        sub_title: MEng in Operations Research, Financial Engineering
        caption: 2022 - 2023
        description: |
          GPA - 4.0
          - *Selected Coursework* - Machine Learning, Reinforcement Learning, Big Data Technologies, Optimization, Monte Carlo Simulation, Time Series Analysis, Game Theory, Portfolio Management
          
      - layout: top
        title: IIT Madras
        sub_title: BTech in Mechanical Engineering
        caption: 2016 - 2020
        description: |
          GPA - 3.86
            - *Selected Coursework* - Data Structures and Algorithms, Numerical Programming Methods
  - title: Research & Projects
    layout: list
    content:
      - layout: top
        border: weak
        title: Exploratory Analysis between Realized and Implied Volatility of the S&P 500 Index
        sub_title: Cornell University
        caption: January - March 2023
        description: |
         
          - Studied the underlying dynamics and distribution of Volatility Risk Premium for the S&P 500 using historic options data
          - Analyzed and fitted multivariate Generalized Normal Distribution (GND) using R to predict future volatility in the market
      - layout: top
        border: weak
        title: Neural-Network based approach to Non-Linear Pairs-Trading
        sub_title: IAQF Student Competition 2023
        caption: January - February 2023
        description: |
          - Developed a testing algorithm that identifies and quantifies non-linear relationships between ETFs for pairs-trading
          - Built a neural-network based approach to capture non-linear patterns; achieved superior results compared to linear strategies
      - layout: top
        border: weak
        title: Generative Adversarial Networks (GAN) for Cryptocurrency Trading
        sub_title: Cornell University
        caption: August - October 2022
        description: |
         
          - Trained a TimeGAN model to generate synthetic cryptocurrency price time-series data using Tensorflow and Keras
          - Implemented the modified Autoencoder network in cryptocurrency price forecasting & predictive models for trading
      - layout: top
        border: weak
        title: Spatial Convolutional Neural Networks (CNN) for Heat Transfer Model
        sub_title: IIT Madras
        caption: January - December 2019
        description: |
         
          - Trained a 3-D CNN to predict the outcome of Computational Thermodynamics software for complex fin shapes
          - Reduced run-time for complex cases (from days to a few minutes) when using the model as the initial field in a simulation
      - layout: top
        border: weak
        title: Modeling Chaotic Quantum Mechanical Systems
        sub_title: IIT Madras
        caption: July 2018 - June 2019
        description: |
         
          - Performed optimized high-dimension matrix operations using Random Matrix Theory (RMT), modeling a quantum operator
          - Studied the eigen-phase & spacing distributions, and Lyapunov exponent for different RM statistical distributions
  - title: A Little More About Me
    layout: text
    content: |
      During my free time, I like to play badminton and chess. As a hobby, I read/watch intriguing stuff like Wall Street stories, theoretical physics, space exploration, quantum computing, etc. I like to meet new people and hear about different perspectives.

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
